version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'automated'
    allow:
      - dependency-type: 'all'
    versioning-strategy: 'auto'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    # Enable automated merging
    auto-merge-settings:
      enabled: true
      merge-strategy: 'squash'
      # Require all checks to pass before merging
      required-checks:
        - 'build'
        - 'test'
        - 'lint'
